package com.majordaftapps.sshpeaches.app.ui.testing

object UiTestTags {
    const val ABOUT_DIALOG = "about_dialog"
    const val ABOUT_WEBSITE_LINK = "about_website_link"
    const val ABOUT_LICENSES_LINK = "about_licenses_link"
    const val ABOUT_SUPPORT_LINK = "about_support_link"
    const val ABOUT_PRIVACY_LINK = "about_privacy_link"
    const val DRAWER_SCROLL_CONTAINER = "drawer_scroll_container"
    const val SCREEN_HOME = "screen_home"
    const val SCREEN_FAVORITES = SCREEN_HOME
    const val SCREEN_CONNECTING = "screen_connecting"
    const val SCREEN_HOSTS = "screen_hosts"
    const val SCREEN_UPTIME = "screen_uptime"
    const val SCREEN_IDENTITIES = "screen_identities"
    const val SCREEN_FORWARDS = "screen_forwards"
    const val SCREEN_SNIPPETS = "screen_snippets"
    const val SCREEN_SNIPPET_EDITOR = "screen_snippet_editor"
    const val SCREEN_KEYBOARD = "screen_keyboard"
    const val SCREEN_THEME_EDITOR = "screen_theme_editor"
    const val SCREEN_THEME_PROFILE_EDITOR = "screen_theme_profile_editor"
    const val SCREEN_SETTINGS = "screen_settings"
    const val SCREEN_OPEN_SOURCE_LICENSES = "screen_open_source_licenses"
    fun openSessionAction(sessionId: String, action: String): String = "open_session_${sessionId}_$action"
    const val HOME_WELCOME = "home_welcome"
    const val HOME_WELCOME_ADD_HOST = "home_welcome_add_host"
    const val HOME_WELCOME_ADD_IDENTITY = "home_welcome_add_identity"
    const val HOME_WELCOME_ADD_FORWARD = "home_welcome_add_forward"
    const val HOME_WELCOME_ADD_SNIPPET = "home_welcome_add_snippet"
    const val HOME_RECENTS_SECTION = "home_recents_section"
    fun homeRecentItem(key: String): String = "home_recent_${sanitize(key)}"
    fun homeRecentOverflowButton(key: String): String = "home_recent_${sanitize(key)}_overflow_button"
    fun homeRecentOverflowAction(key: String, action: String): String =
        "home_recent_${sanitize(key)}_overflow_${sanitize(action)}"
    fun homeFavoriteOverflowButton(key: String): String = "home_favorite_${sanitize(key)}_overflow_button"
    fun homeFavoriteOverflowAction(key: String, action: String): String =
        "home_favorite_${sanitize(key)}_overflow_${sanitize(action)}"

    const val DRAWER_QUICK_CONNECT = "drawer_quick_connect"
    fun drawerItem(route: String): String = "drawer_item_$route"
    const val QUICK_CONNECT_HOST_INPUT = "quick_connect_host_input"
    const val QUICK_CONNECT_PORT_INPUT = "quick_connect_port_input"
    const val QUICK_CONNECT_USERNAME_INPUT = "quick_connect_username_input"
    const val QUICK_CONNECT_PASSWORD_INPUT = "quick_connect_password_input"
    const val QUICK_CONNECT_CONNECT_BUTTON = "quick_connect_connect_button"
    const val QUICK_CONNECT_STATUS_TEXT = "quick_connect_status_text"

    const val HOST_ADD_BUTTON = "host_add_button"
    const val HOST_IMPORT_BUTTON = "host_import_button"
    const val HOST_SEARCH_INPUT = "host_search_input"
    const val HOST_SORT_FIELD = "host_sort_field"
    fun hostAction(id: String, action: String): String = "host_${id}_action_$action"
    fun hostFavorite(id: String): String = "host_${id}_favorite"
    fun hostOverflowButton(id: String): String = "host_${id}_overflow_button"
    fun hostOverflowAction(id: String, action: String): String = "host_${id}_overflow_$action"
    const val HOST_QR_DIALOG = "host_qr_dialog"
    const val HOST_EXPORT_PASSWORD_DIALOG = "host_export_password_dialog"
    const val HOST_EXPORT_PASSWORD_INPUT = "host_export_password_input"
    const val HOST_EXPORT_PASSWORD_CONFIRM_INPUT = "host_export_password_confirm_input"
    const val HOST_EXPORT_PASSWORD_CONFIRM_BUTTON = "host_export_password_confirm_button"
    const val HOST_DIALOG_NAME_INPUT = "host_dialog_name_input"
    const val HOST_DIALOG_HOST_INPUT = "host_dialog_host_input"
    const val HOST_DIALOG_PORT_INPUT = "host_dialog_port_input"
    const val HOST_DIALOG_USERNAME_INPUT = "host_dialog_username_input"
    const val HOST_DIALOG_SCROLL = "host_dialog_scroll"
    const val HOST_DIALOG_AUTH_FIELD = "host_dialog_auth_field"
    fun hostDialogAuthOption(authMethodName: String): String = "host_dialog_auth_option_$authMethodName"
    const val HOST_DIALOG_CONFIRM_BUTTON = "host_dialog_confirm_button"
    const val HOST_DIALOG_CANCEL_BUTTON = "host_dialog_cancel_button"
    const val HOST_DIALOG_ERROR = "host_dialog_error"

    const val UPTIME_ADD_BUTTON = "uptime_add_button"
    const val UPTIME_HOST_PICKER = "uptime_host_picker"
    fun uptimeHostOption(hostId: String): String = "uptime_host_option_$hostId"
    const val UPTIME_METHOD_FIELD = "uptime_method_field"
    fun uptimeMethodOption(method: String): String = "uptime_method_option_$method"
    const val UPTIME_PORT_INPUT = "uptime_port_input"
    const val UPTIME_INTERVAL_INPUT = "uptime_interval_input"
    const val UPTIME_ENABLED_SWITCH = "uptime_enabled_switch"
    const val UPTIME_SAVE_BUTTON = "uptime_save_button"
    const val UPTIME_CANCEL_BUTTON = "uptime_cancel_button"
    const val UPTIME_EMPTY_SAVED_HOSTS = "uptime_empty_saved_hosts"
    const val UPTIME_EMPTY_MONITORS = "uptime_empty_monitors"
    fun uptimeCard(hostId: String): String = "uptime_card_$hostId"
    fun uptimeRefresh(hostId: String): String = "uptime_refresh_$hostId"
    fun uptimeEdit(hostId: String): String = "uptime_edit_$hostId"
    fun uptimeRemove(hostId: String): String = "uptime_remove_$hostId"
    fun uptimeEnabled(hostId: String): String = "uptime_enabled_$hostId"

    const val IDENTITY_SEARCH_INPUT = "identity_search_input"
    const val IDENTITY_ADD_BUTTON = "identity_add_button"
    const val IDENTITY_IMPORT_BUTTON = "identity_import_button"
    const val IDENTITY_GROUP_FIELD = "identity_group_field"
    const val IDENTITY_DIALOG_LABEL_INPUT = "identity_dialog_label_input"
    const val IDENTITY_DIALOG_GENERATE_BUTTON = "identity_dialog_generate_button"
    const val IDENTITY_DIALOG_FINGERPRINT_INPUT = "identity_dialog_fingerprint_input"
    fun identityFavorite(id: String): String = "identity_${id}_favorite"
    fun identityShare(id: String): String = "identity_${id}_share"
    fun identityOverflowButton(id: String): String = "identity_${id}_overflow_button"
    fun identityOverflowAction(id: String, action: String): String = "identity_${id}_overflow_$action"
    const val IDENTITY_SHARE_PASSPHRASE_INPUT = "identity_share_passphrase_input"
    const val IDENTITY_SHARE_CONFIRM_PASSPHRASE_INPUT = "identity_share_confirm_passphrase_input"
    const val IDENTITY_CARD_EDIT_BUTTON = "identity_card_edit_button"
    const val IDENTITY_CARD_DELETE_BUTTON = "identity_card_delete_button"

    const val FORWARD_SEARCH_INPUT = "forward_search_input"
    const val FORWARD_ADD_BUTTON = "forward_add_button"
    const val FORWARD_IMPORT_BUTTON = "forward_import_button"
    const val FORWARD_GROUP_FIELD = "forward_group_field"
    const val FORWARD_DIALOG_LABEL_INPUT = "forward_dialog_label_input"
    const val FORWARD_DIALOG_BIND_INPUT = "forward_dialog_bind_input"
    const val FORWARD_DIALOG_SOURCE_PORT_INPUT = "forward_dialog_source_port_input"
    const val FORWARD_DIALOG_HOST_FIELD = "forward_dialog_host_field"
    const val FORWARD_HOST_BACKGROUND_ERROR = "forward_host_background_error"
    fun forwardHostOption(hostId: String): String = "forward_host_option_$hostId"
    const val FORWARD_DIALOG_DEST_HOST_INPUT = "forward_dialog_dest_host_input"
    const val FORWARD_DIALOG_DEST_PORT_INPUT = "forward_dialog_dest_port_input"
    fun forwardFavorite(id: String): String = "forward_${id}_favorite"
    fun forwardShare(id: String): String = "forward_${id}_share"
    fun forwardOverflowButton(id: String): String = "forward_${id}_overflow_button"
    fun forwardOverflowAction(id: String, action: String): String = "forward_${id}_overflow_$action"
    const val FORWARD_CARD_EDIT_BUTTON = "forward_card_edit_button"
    const val FORWARD_CARD_DELETE_BUTTON = "forward_card_delete_button"

    const val SNIPPET_SEARCH_INPUT = "snippet_search_input"
    const val SNIPPET_ADD_BUTTON = "snippet_add_button"
    const val SNIPPET_IMPORT_BUTTON = "snippet_import_button"
    const val SNIPPET_EDITOR_GROUP_INPUT = "snippet_editor_group_input"
    const val SNIPPET_EDITOR_TITLE_INPUT = "snippet_editor_title_input"
    const val SNIPPET_EDITOR_DESCRIPTION_INPUT = "snippet_editor_description_input"
    const val SNIPPET_EDITOR_COMMAND_INPUT = "snippet_editor_command_input"
    fun snippetRun(id: String): String = "snippet_${id}_run"
    fun snippetEdit(id: String): String = "snippet_${id}_edit"
    fun snippetDelete(id: String): String = "snippet_${id}_delete"
    fun snippetOverflowButton(id: String): String = "snippet_${id}_overflow_button"
    fun snippetOverflowAction(id: String, action: String): String = "snippet_${id}_overflow_$action"

    fun groupHeader(vertical: String, group: String): String = "group_header_${sanitize(vertical)}_${sanitize(group)}"
    fun groupToggle(vertical: String, group: String): String = "group_toggle_${sanitize(vertical)}_${sanitize(group)}"
    fun topBarAdd(route: String): String = "top_bar_add_${sanitize(route)}"
    fun topBarImport(route: String): String = "top_bar_import_${sanitize(route)}"
    const val DELETE_CONFIRM_DIALOG = "delete_confirm_dialog"
    const val DELETE_CONFIRM_BUTTON = "delete_confirm_button"
    const val DELETE_CANCEL_BUTTON = "delete_cancel_button"

    const val KEYBOARD_RESET_BUTTON = "keyboard_reset_button"
    fun keyboardSlot(index: Int): String = "keyboard_slot_$index"
    const val KEYBOARD_EDITOR_BACK_BUTTON = "keyboard_editor_back_button"
    const val KEYBOARD_EDITOR_TEXT_INPUT = "keyboard_editor_text_input"
    const val KEYBOARD_EDITOR_USE_TEXT_BUTTON = "keyboard_editor_use_text_button"
    const val KEYBOARD_EDITOR_ADVANCED_BUTTON = "keyboard_editor_advanced_button"
    const val KEYBOARD_EDITOR_SEQUENCE_INPUT = "keyboard_editor_sequence_input"
    const val KEYBOARD_EDITOR_USE_SEQUENCE_BUTTON = "keyboard_editor_use_sequence_button"

    const val THEME_DEFAULT_FIELD = "theme_default_field"
    const val THEME_CREATE_BUTTON = "theme_create_button"
    fun themeDefaultOption(name: String): String =
        "theme_default_option_" + name.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
    fun themeDuplicate(id: String): String = "theme_${id}_duplicate"
    fun themeEdit(id: String): String = "theme_${id}_edit"
    fun themeDelete(id: String): String = "theme_${id}_delete"
    const val THEME_DELETE_CONFIRM = "theme_delete_confirm"
    const val THEME_DELETE_CANCEL = "theme_delete_cancel"
    const val THEME_PROFILE_NAME_INPUT = "theme_profile_name_input"
    const val THEME_PROFILE_FONT_BUTTON = "theme_profile_font_button"
    const val THEME_PROFILE_FONT_FIELD = "theme_profile_font_field"
    fun themeProfileFontOption(name: String): String =
        "theme_profile_font_option_" + name.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
    const val THEME_PROFILE_SAVE_BUTTON = "theme_profile_save_button"
    const val THEME_PROFILE_CANCEL_BUTTON = "theme_profile_cancel_button"
    const val THEME_PROFILE_ERROR = "theme_profile_error"

    const val SETTINGS_THEME_MODE_FIELD = "settings_theme_mode_field"
    fun settingsThemeOption(name: String): String =
        "settings_theme_option_" + name.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
    fun settingsAppIconOption(name: String): String =
        "settings_app_icon_option_" + name.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
    fun settingsTerminalOption(name: String): String =
        "settings_terminal_option_" + name.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
    fun settingsTerminalBellOption(name: String): String =
        "settings_terminal_bell_option_" + name.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
    const val SETTINGS_SCROLL_CONTAINER = "settings_scroll_container"
    const val SETTINGS_BACKGROUND_SWITCH = "settings_background_switch"
    const val SETTINGS_TERMINAL_EMULATION_FIELD = "settings_terminal_emulation_field"
    const val SETTINGS_TERMINAL_BELL_FIELD = "settings_terminal_bell_field"
    const val SETTINGS_TERMINAL_VOLUME_BUTTONS_SWITCH = "settings_terminal_volume_buttons_switch"
    const val SETTINGS_TERMINAL_MARGIN_INPUT = "settings_terminal_margin_input"
    const val SETTINGS_MOSH_SERVER_COMMAND_INPUT = "settings_mosh_server_command_input"
    const val SETTINGS_DIAGNOSTICS_SWITCH = "settings_diagnostics_switch"
    const val SETTINGS_INCLUDE_SECRETS_SWITCH = "settings_include_secrets_switch"
    const val SETTINGS_BIOMETRIC_SWITCH = "settings_biometric_switch"
    const val SETTINGS_PIN_STATUS_TEXT = "settings_pin_status_text"
    const val SETTINGS_SET_PIN_BUTTON = "settings_set_pin_button"
    const val SETTINGS_DISABLE_PIN_BUTTON = "settings_disable_pin_button"
    const val SETTINGS_PIN_DIALOG = "settings_pin_dialog"
    const val SETTINGS_PIN_INPUT = "settings_pin_input"
    const val SETTINGS_PIN_CONFIRM_INPUT = "settings_pin_confirm_input"
    const val SETTINGS_PIN_SAVE_BUTTON = "settings_pin_save_button"
    const val SETTINGS_DISABLE_PIN_CONFIRM = "settings_disable_pin_confirm"
    const val SETTINGS_HOST_KEY_PROMPT_SWITCH = "settings_host_key_prompt_switch"
    const val SETTINGS_AUTO_TRUST_HOST_KEY_SWITCH = "settings_auto_trust_host_key_switch"
    const val SETTINGS_RESTORE_DEFAULTS_BUTTON = "settings_restore_defaults_button"
    const val SETTINGS_RESTORE_DEFAULTS_CONFIRM = "settings_restore_defaults_confirm"
    const val SETTINGS_EXPORT_QR_BUTTON = "settings_export_qr_button"
    const val SETTINGS_EXPORT_DIALOG = "settings_export_dialog"
    const val SETTINGS_EXPORT_PASSPHRASE_INPUT = "settings_export_passphrase_input"
    const val SETTINGS_EXPORT_CONFIRM_PASSPHRASE_INPUT = "settings_export_confirm_passphrase_input"
    const val SETTINGS_EXPORT_GENERATE_BUTTON = "settings_export_generate_button"
    const val SETTINGS_EXPORT_ERROR = "settings_export_error"
    const val SETTINGS_EXPORT_QR_DIALOG = "settings_export_qr_dialog"
    const val PERMISSION_REQUIRED_DIALOG = "permission_required_dialog"
    const val PERMISSION_REQUIRED_MANAGE_BUTTON = "permission_required_manage_button"
    const val PERMISSION_REQUIRED_REQUEST_BUTTON = "permission_required_request_button"

    const val CONNECTING_RETRY_BUTTON = "connecting_retry_button"
    const val CONNECTING_TERMINAL_PANEL = "connecting_terminal_panel"
    const val CONNECTING_SFTP_PANEL = "connecting_sftp_panel"
    const val CONNECTING_SCP_PANEL = "connecting_scp_panel"
    const val CONNECTING_LOG_PANEL = "connecting_log_panel"
    const val CONNECTING_FIND_BUTTON = "connecting_find_button"
    const val CONNECTING_CLOSE_BUTTON = "connecting_close_button"
    const val CONNECTING_KEYBOARD_TOGGLE = "connecting_keyboard_toggle"
    const val CONNECTING_FIND_INPUT = "connecting_find_input"
    const val CONNECTING_FIND_STATUS = "connecting_find_status"
    const val CONNECTING_SNIPPET_PICKER = "connecting_snippet_picker"
    const val CONNECTING_SFTP_CONSOLE = "connecting_sftp_console"
    const val CONNECTING_SFTP_COMMAND_INPUT = "connecting_sftp_command_input"
    const val CONNECTING_SFTP_RUN_BUTTON = "connecting_sftp_run_button"
    const val CONNECTING_SFTP_HELP_BUTTON = "connecting_sftp_help_button"
    const val CONNECTING_SFTP_REFRESH_BUTTON = "connecting_sftp_refresh_button"
    const val CONNECTING_SFTP_STATUS_STRIP = "connecting_sftp_status_strip"
    const val CONNECTING_SCP_REMOTE_DIR_INPUT = "connecting_scp_remote_dir_input"
    const val CONNECTING_SCP_DOWNLOAD_REMOTE_INPUT = "connecting_scp_download_remote_input"
    const val CONNECTING_SCP_DOWNLOAD_LOCAL_INPUT = "connecting_scp_download_local_input"
    const val CONNECTING_SCP_DOWNLOAD_BUTTON = "connecting_scp_download_button"
    const val CONNECTING_SCP_OPEN_UPLOAD_BUTTON = "connecting_scp_open_upload_button"
    const val CONNECTING_SCP_UPLOAD_LOCAL_INPUT = "connecting_scp_upload_local_input"
    const val CONNECTING_SCP_UPLOAD_REMOTE_INPUT = "connecting_scp_upload_remote_input"
    const val CONNECTING_SCP_UPLOAD_BUTTON = "connecting_scp_upload_button"
    const val CONNECTING_SCP_BACK_TO_DOWNLOAD_BUTTON = "connecting_scp_back_to_download_button"
    const val CONNECTING_SCP_ACTIVITY_LOG = "connecting_scp_activity_log"
    const val CONNECTING_SCP_ACTIONS_BUTTON = "connecting_scp_actions_button"
    const val CONNECTING_SCP_TRANSFER_STRIP = "connecting_scp_transfer_strip"
    const val CONNECTING_SCP_STATUS_STRIP = "connecting_scp_status_strip"
    const val CONNECTING_SCP_RENAME_DIALOG = "connecting_scp_rename_dialog"
    const val CONNECTING_SCP_MOVE_DIALOG = "connecting_scp_move_dialog"
    const val CONNECTING_SCP_NEW_FOLDER_DIALOG = "connecting_scp_new_folder_dialog"
    const val CONNECTING_SCP_DELETE_DIALOG = "connecting_scp_delete_dialog"
    const val CONNECTING_SCP_RENAME_INPUT = "connecting_scp_rename_input"
    const val CONNECTING_SCP_MOVE_INPUT = "connecting_scp_move_input"
    const val CONNECTING_SCP_NEW_FOLDER_INPUT = "connecting_scp_new_folder_input"
    fun connectingScpAction(name: String): String = "connecting_scp_action_${sanitize(name)}"
    fun connectingScpBreadcrumb(path: String): String = "connecting_scp_breadcrumb_${sanitize(path)}"
    fun connectingScpRemoteRow(path: String): String = "connecting_scp_remote_row_${sanitize(path)}"
    fun connectingScpRemoteOpen(path: String): String = "connecting_scp_remote_open_${sanitize(path)}"
    fun connectingCompactKey(index: Int): String = "connecting_compact_key_$index"

    const val HOST_KEY_PROMPT_DIALOG = "host_key_prompt_dialog"
    const val HOST_KEY_PROMPT_ACCEPT = "host_key_prompt_accept"
    const val HOST_KEY_PROMPT_ACCEPT_ALWAYS = "host_key_prompt_accept_always"
    const val HOST_KEY_PROMPT_REJECT = "host_key_prompt_reject"

    const val PASSWORD_PROMPT_DIALOG = "password_prompt_dialog"
    const val PASSWORD_PROMPT_INPUT = "password_prompt_input"
    const val PASSWORD_PROMPT_CONFIRM = "password_prompt_confirm"
    const val PASSWORD_PROMPT_CANCEL = "password_prompt_cancel"

    const val LOCK_SCREEN_OVERLAY = "lock_screen_overlay"
    const val LOCK_SCREEN_PIN_INPUT = "lock_screen_pin_input"
    const val LOCK_SCREEN_UNLOCK_BUTTON = "lock_screen_unlock_button"
    const val LOCK_SCREEN_BIOMETRIC_BUTTON = "lock_screen_biometric_button"

    private fun sanitize(value: String): String =
        value.lowercase().replace(Regex("[^a-z0-9]+"), "_").trim('_')
}
